apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-client-service"
  labels:
    app: {{ .Chart.Name }}-client
spec:
  type: NodePort
  selector:
    app: {{ .Chart.Name }}-client
  ports:
    - name: http
      port: {{ $.Values.client.port }}
      nodePort: {{ $.Values.client.nodePort }}
