apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-client"
  labels:
    app: "{{ .Chart.Name }}-client"
spec:
  selector:
    app: "{{ .Chart.Name }}-client"
  ports:
  - port: {{ $.Values.client.port }}
    targetPort: {{ $.Values.client.port }}
