apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-server"
  labels:
    app: "{{ .Chart.Name }}-server"
spec:
  selector:
    app: "{{ .Chart.Name }}-server"
  ports:
  - port: {{ $.Values.server.port }}
    targetPort: {{ $.Values.server.port }}
