apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-server-service"
  labels:
    app: {{ .Chart.Name }}-server
spec:
  type: NodePort
  selector:
    app: {{ .Chart.Name }}-server
  ports:
    - name: http
      port: {{ $.Values.server.port }}
      nodePort: {{ $.Values.server.nodePort }}
